import "./globals.css";
import SideBar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "santoshi" }}>
        <div className="h-full">
          <div className="xl:flex ">
            <div className="xs:hidden xl:block bg-white">
              <SideBar />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
